FROM python:3.9-slim

WORKDIR /app
COPY requirements.txt facade_service.py /app/
RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 5001
ENV PYTHONUNBUFFERED=1
CMD ["uvicorn", "facade_service:app", "--host", "0.0.0.0", "--port", "5001"]