FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt message_service.py /app/
RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 5005
ENV PYTHONUNBUFFERED=1
CMD ["uvicorn", "message_service:app", "--host", "0.0.0.0", "--port", "5005"]

